# Generated by Django 5.1.4 on 2025-01-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_answer_voter_question_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='view_cut',
            field=models.IntegerField(default=0),
        ),
    ]
